### ISSUE TITLE
Colab + Gradio

### ISSUE THREAD

**Issue by tushar-31093** [NisaarAgharia/Indian-LawyerGPT#5]
Hi,
I tried running it on Colab (15GB, Free) with a Gradio interface and the sessions just crashes due to memory issues. Is there a way to run in on colab unless I pay for the Pro version?

**Comment by NisaarAgharia** [comment]
The training can be done on free gpu provided by collab.

Which files are you running?

**Comment by tushar-31093** [comment]
I am only trying the inference. Training is fine.

Well, apparantly i am trying to download your model from hugging face and trying to use it. I may be getting it wrong on how it works. You model in HF is an addition to the base Falcon7B or is it a standard model in itself when loaded in a quanized fashion? My notebook crashes at this part...The system memory gets completely full and it crashes. The GPU is not used.

![image](https://github.com/NisaarAgharia/Indian-LawyerGPT/assets/40886260/6f656716-de18-4654-9ea4-d6fc167f984d)

**Comment by tushar-31093** [comment]
> I am only trying the inference. Training is fine.
> 
> Well, apparantly i am trying to download your model from hugging face and trying to use it. I may be getting it wrong on how it works. You model in HF is an addition to the base Falcon7B or is it a standard model in itself when loaded in a quanized fashion? My notebook crashes at this part...The system memory gets completely full and it crashes. The GPU is not used.
> 
> ![image](https://user-images.githubusercontent.com/40886260/250348882-6f656716-de18-4654-9ea4-d6fc167f984d.png)

![image](https://github.com/NisaarAgharia/Indian-LawyerGPT/assets/40886260/d7b4c878-20a1-4c04-a248-d2e7a32b2cdf)

It crashed after this screenshot

**Comment by NisaarAgharia** [comment]
I can see you ram is not enough it's crashing. You need high-ram runtime environment.

you will need collab-pro for that i guess

**Comment by tushar-31093** [comment]
> I can see you ram is not enough it's crashing. You need high-ram runtime environment.
> 
> you will need collab-pro for that i guess

I fixed it. I ended up using a sharded model for this and it worked.

Also, any idea on how to give this an interface like Gradio or Streamlit? Just a question. 

Lastly, the generation does take time. Any hints on how it can be sped up?

**Comment by NisaarAgharia** [comment]
you can increase the speed of the inference by loading it in 8Bit or Doing Batch Inference

there is a collab notebook called faster-llm-inference in the project that showcases all the types of loading the model and faster inference options

**Comment by tushar-31093** [comment]
> you can increase the speed of the inference by loading it in 8Bit or Doing Batch Inference
> 
> there is a collab notebook called faster-llm-inference in the project that showcases all the types of loading the model and faster inference options

Can you try this from Hugging Face? its not as fast as I assumed.

tushar310/model_law_falcon7b

**Comment by NisaarAgharia** [comment]
With batch inference i have been able to generate outputs within 3 seconds.

Which gpu are you using.

**Comment by tushar-31093** [comment]
> 

I am on free tier, T4 GPU. If it train it using a sharded version it trains just fine. I visited other falcon7b tutorials for that. The only issue being that the results generate are more of halucinations and garble information. 

If i use your version of facon7b that you used, i cannot train a model in this colab GPU unless i get a pro version with higher vGPU config.

I could share my training ipynb file with you to try it out in case that works? 
Also, Did you run it using HF repo or yours? 
Can you share the snapshots of the generated results you are getting? 

As far as I know, for every question there should be a single appropriate respose but after training it and generating responses it just goes crazy. A lot of redundant data and informaion.

**Comment by tushar-31093** [comment]
> Inference doesn't work on free tier.
> 
> Few things i would suggest
> 
> * Train the model with better hyper parameters . Epoch 3-4 , steps > epoch * number of training examples,
>   After training store it on your hugging face repo.
>   Try reducing the loss < 0.1
> * run the inference on pro version with faster llm notebook.
>   Try batch inference or 8bit inference for faster inference
> 
> -yes i am using hugging face for model and datasets loading

Fair... 
I just wanted to see how this works on colab on free tier as there are many people out there claiming to be running and executing it on colab. It surely has it own set of limitations.

Possible to share the results of your batch query or something? I am not convinced how these models our performing on the data we have now. The one that was shared with you as well. 

Would be great to validate this based on the results themselves else I follow some other approach.
