### ISSUE TITLE
How can I create own dataset

### ISSUE THREAD

**Issue by Charanjit5145** [NisaarAgharia/Indian-LawyerGPT#7]
Facing issue to create a dataset with raw files like multiple pdfs text files or word files how can I directly use them if not how can I convert into json format

**Comment by NisaarAgharia** [comment]
to pass multiple pdf and raw files you will have to continue pretraining process or

to convert into json , you will have to create short summaries , description and then create instruction dataset in this format  using gpt3.5 or gpt4 
{"instruction": "Identify and summarize the key....", "input": "Kantaru Rajeevaru ....", "output": "..."}
